### ISSUE TITLE
latexlive网页下面给出的邮箱地址无效

### ISSUE THREAD

**Issue by 1357310795** [mommytalkltd/LaTeXLive#12]
上午发现了服务器的证书问题，本想发个邮件提醒一下妈咪叔的
![image](https://user-images.githubusercontent.com/35869804/164885141-65fb5501-4d16-4972-8abf-650a30f9f3e5.png)

但是现在才发现，邮件没能成功发出去
![image](https://user-images.githubusercontent.com/35869804/164885127-fe089ee7-4720-4a00-acaf-6ef4aadffdaa.png)

***
题外话，感谢妈咪叔及时把证书问题解决了（#11），latexlive网站真的对我帮助很大！

**Comment by PhysicsTV** [comment]
我打开不了latexlive了

**Comment by mommytalkltd** [comment]
您一看就是内行，我们琢磨了好久才发现问题在哪。。
