### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by 1357310795** [mommytalkltd/LaTeXLive#26]
![image](https://user-images.githubusercontent.com/35869804/191697283-92b37c39-abb9-4c43-8d08-f87da125595d.png)

Microsoft Edge 版本 105.0.1343.42 (正式版本) (64 位)
Windows 10 21H1

**Comment by roycham** [comment]
＋1

**Comment by Sped0n** [comment]
我这边也是

**Comment by roycham** [comment]
我这边刚才登陆成功了
Firefox 105.0 
Windows 10 专业版 21H2

**Comment by 1357310795** [comment]
> 我这边刚才登陆成功了 Firefox 105.0 Windows 10 专业版 21H2

确实，我也成功了
